---
username: gmarafon

configure_brew: true
configure_dotfiles: true
configure_finder: true
configure_dock: true
configure_keys: true
configure_ui: false


dotfiles_repo: https://github.com/scirons/dotfiles.git
dotfiles_dir: ~/.dotfiles


taps:
  - nikitabobko/tap
  - FelixKratz/formulae

packages:
  - tmux
  - neovim
  - kitty
  - htop
  - yazi
  - pure
  - font-terminess-ttf-nerd-font
  - zsh-autosuggestions
  - zsh-syntax-highlighting
  - font-sketchybar-app-font
  - font-sf-pro
  - sf-symbols
  - font-symbols-only-nerd-font
  - neofetch
  - git
  - git-lfs
  - secretive
  - rclone
  - nmap
  - mpv
  - ansible
  - terraform
  - qemu
  - iperf3
  - speedtest-cli
  - ffmpeg
  - gnupg
  - gpg-suite
  - newsboat
  - obsidian
  - visual-studio-code
  - figma
  - pandoc
  - translate-shell
  - imagemagick
  - fzf
  - arp-scan
  - wireshark

tap_packages:
  - sketchybar
  - aerospace
